# Generated by Django 5.2.7 on 2025-11-26 13:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='endereço de e-mail')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AutoavaliacaoEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('humor', models.IntegerField(help_text='De 1 (muito triste) a 10 (muito feliz)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nível de humor')),
                ('ansiedade', models.IntegerField(help_text='De 1 (nenhuma) a 10 (muita ansiedade)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nível de ansiedade')),
                ('estresse', models.IntegerField(help_text='De 1 (nenhum) a 10 (muito estresse)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nível de estresse')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações livres')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Autoavaliação Emocional',
                'verbose_name_plural': 'Autoavaliações Emocionais',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da consulta')),
                ('horario', models.TimeField(verbose_name='Horário da consulta')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada_paciente', 'Cancelada pelo paciente'), ('cancelada_psicologo', 'Cancelada pelo psicólogo'), ('faltou', 'Paciente não compareceu')], default='agendada', max_length=20, verbose_name='Status')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_como_paciente', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota (1 a 5)')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.consulta', verbose_name='Consulta avaliada')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='InteracaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_usuario', models.TextField(verbose_name='Mensagem do usuário')),
                ('resposta_ia', models.TextField(verbose_name='Resposta da IA')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('autoavaliacao_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.autoavaliacaoemocional', verbose_name='Autoavaliação associada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Interação com IA',
                'verbose_name_plural': 'Interações com IA',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('sistema', 'Sistema'), ('ia', 'Interação com IA')], default='sistema', max_length=20)),
                ('mensagem', models.TextField(verbose_name='Conteúdo')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('crp', models.CharField(help_text='Ex: 01/123456', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='O CRP deve seguir o formato XX/XXXXXX (ex: 06/123456).', regex='^\\d{2}/\\d{6}$')], verbose_name='CRP')),
                ('especialidades', models.TextField(blank=True, help_text='Ex: Terapia cognitivo-comportamental, Ansiedade, Depressão', verbose_name='Especialidades')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário vinculado')),
            ],
            options={
                'verbose_name': 'Psicólogo',
                'verbose_name_plural': 'Psicólogos',
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='app.psicologo', verbose_name='Psicólogo'),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psicologo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.psicologo', verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Fim')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponiveis', to='app.psicologo', verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Horário Disponível',
                'verbose_name_plural': 'Horários Disponíveis',
                'unique_together': {('psicologo', 'dia_semana', 'hora_inicio', 'hora_fim')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together={('psicologo', 'data', 'horario')},
        ),
    ]
