# Generated by Django 5.2.7 on 2025-11-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariodisponivel',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_list', to='app.psicologo', verbose_name='Psicólogo'),
        ),
    ]
